### ISSUE TITLE
Missing software license

### ISSUE THREAD

**Issue by h3xx** [hek/hek#6]
This project does not state its software license explicitly.

**Comment by johnstt** [comment]
So make a pull request and write on your resume that you contributed to open source?

**Comment by jtimberman** [comment]
It's BSD licensed according to the [package.json](https://github.com/starters/kik/blob/master/package.json#L23).

I agree that it would be good to have a specific LICENSE file in the root of the project, and header comments in all source code files, however.

**Comment by azer** [comment]
I've changed it as WTFPL.
